use std::env;
use std::error::Error;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use brotli::CompressorWriter;
use flate2::Compression;
use flate2::write::GzEncoder;
use sha2::{Digest, Sha256};

const FALLBACK_INDEX: &str = r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>termd</title>
    <style>
      body { font-family: system-ui, sans-serif; margin: 2rem; line-height: 1.5; }
      code { background: #f3f4f6; padding: 0.125rem 0.25rem; border-radius: 0.25rem; }
    </style>
  </head>
  <body>
    <h1>termd Web</h1>
    <p>这个二进制没有嵌入已构建的 Web UI。发布构建会自动嵌入 <code>termui/frontend/dist</code>。</p>
  </body>
</html>
"#;

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-env-changed=TERMD_WEB_SOURCE_DIR");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let embedded_dir = out_dir.join("embedded-web");
    if embedded_dir.exists() {
        fs::remove_dir_all(&embedded_dir)?;
    }
    fs::create_dir_all(&embedded_dir)?;

    let files = match resolve_source_dir()? {
        Some(source_dir) => {
            emit_rerun_for_tree(&source_dir)?;
            copy_tree(&source_dir, &embedded_dir)?
        }
        None => {
            let fallback = embedded_dir.join("index.html");
            fs::write(&fallback, FALLBACK_INDEX)?;
            vec![PathBuf::from("index.html")]
        }
    };

    write_generated_assets(&out_dir, &files)?;
    Ok(())
}

fn resolve_source_dir() -> Result<Option<PathBuf>, Box<dyn Error>> {
    if let Some(raw) = env::var_os("TERMD_WEB_SOURCE_DIR") {
        let path = PathBuf::from(raw);
        let resolved = if path.is_absolute() {
            path
        } else {
            env::current_dir()?.join(path)
        };
        emit_rerun_for_candidate(&resolved);
        if has_index_html(&resolved) {
            return Ok(Some(resolved));
        }
    }

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let workspace_dist = manifest_dir.join("../termui/frontend/dist");
    emit_rerun_for_candidate(&workspace_dist);
    if has_index_html(&workspace_dist) {
        return Ok(Some(workspace_dist));
    }

    Ok(None)
}

fn emit_rerun_for_candidate(path: &Path) {
    // dist 可能在第一次 Rust 构建后才由前端构建产出；监听目录和 index，避免占位页长期留在 OUT_DIR。
    println!("cargo:rerun-if-changed={}", path.display());
    println!(
        "cargo:rerun-if-changed={}",
        path.join("index.html").display()
    );
}

fn has_index_html(path: &Path) -> bool {
    path.join("index.html").is_file()
}

fn emit_rerun_for_tree(path: &Path) -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-changed={}", path.display());
    for entry in fs::read_dir(path)? {
        let entry = entry?;
        let child = entry.path();
        if child.is_dir() {
            emit_rerun_for_tree(&child)?;
        } else {
            println!("cargo:rerun-if-changed={}", child.display());
        }
    }
    Ok(())
}

fn copy_tree(source: &Path, dest: &Path) -> Result<Vec<PathBuf>, Box<dyn Error>> {
    let mut files = Vec::new();
    copy_tree_inner(source, source, dest, &mut files)?;
    files.sort();
    Ok(files)
}

fn copy_tree_inner(
    root: &Path,
    source: &Path,
    dest: &Path,
    files: &mut Vec<PathBuf>,
) -> Result<(), Box<dyn Error>> {
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let source_path = entry.path();
        let rel_path = source_path.strip_prefix(root)?.to_path_buf();
        let dest_path = dest.join(&rel_path);
        if source_path.is_dir() {
            fs::create_dir_all(&dest_path)?;
            copy_tree_inner(root, &source_path, dest, files)?;
        } else {
            if let Some(parent) = dest_path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::copy(&source_path, &dest_path)?;
            files.push(rel_path);
        }
    }
    Ok(())
}

fn write_generated_assets(out_dir: &Path, files: &[PathBuf]) -> Result<(), Box<dyn Error>> {
    let mut generated = String::new();
    generated.push_str("// @generated by termweb/build.rs\n");
    generated.push_str("pub(crate) fn embedded_asset(path: &str) -> Option<EmbeddedAsset> {\n");
    generated.push_str("    match path {\n");
    for file in files {
        let rel = file.to_string_lossy().replace('\\', "/");
        let bytes = fs::read(out_dir.join("embedded-web").join(file))?;
        let digest = Sha256::digest(&bytes);
        let etag = format!("W/\"sha256-{digest:x}\"");
        let rel_literal = rust_string_literal(&rel);
        let include_suffix = rust_string_literal(&format!("/embedded-web/{rel}"));
        let etag_literal = rust_string_literal(&etag);
        let (gzip_suffix, brotli_suffix) = if is_compressible(&rel) {
            let gzip_path = out_dir.join("embedded-web").join(format!("{rel}.gz"));
            let brotli_path = out_dir.join("embedded-web").join(format!("{rel}.br"));
            if let Some(parent) = gzip_path.parent() {
                fs::create_dir_all(parent)?;
            }

            let mut gzip = GzEncoder::new(Vec::new(), Compression::default());
            gzip.write_all(&bytes)?;
            fs::write(&gzip_path, gzip.finish()?)?;

            let mut brotli = Vec::new();
            {
                let mut encoder = CompressorWriter::new(&mut brotli, 4096, 5, 22);
                encoder.write_all(&bytes)?;
            }
            fs::write(&brotli_path, brotli)?;

            (
                Some(rust_string_literal(&format!("/embedded-web/{rel}.gz"))),
                Some(rust_string_literal(&format!("/embedded-web/{rel}.br"))),
            )
        } else {
            (None, None)
        };
        generated.push_str("        ");
        generated.push_str(&rel_literal);
        generated.push_str(
            " => Some(EmbeddedAsset { identity: include_bytes!(concat!(env!(\"OUT_DIR\"), ",
        );
        generated.push_str(&include_suffix);
        generated.push_str(")), gzip: ");
        push_optional_include(&mut generated, gzip_suffix.as_deref());
        generated.push_str(", brotli: ");
        push_optional_include(&mut generated, brotli_suffix.as_deref());
        generated.push_str(", etag: ");
        generated.push_str(&etag_literal);
        generated.push_str(" }),\n");
    }
    generated.push_str("        _ => None,\n");
    generated.push_str("    }\n");
    generated.push_str("}\n");
    fs::write(out_dir.join("assets.rs"), generated)?;
    Ok(())
}

fn push_optional_include(generated: &mut String, suffix: Option<&str>) {
    if let Some(suffix) = suffix {
        generated.push_str("Some(include_bytes!(concat!(env!(\"OUT_DIR\"), ");
        generated.push_str(suffix);
        generated.push_str(")))");
    } else {
        generated.push_str("None");
    }
}

fn is_compressible(path: &str) -> bool {
    matches!(
        path.rsplit('.').next().unwrap_or_default(),
        "css" | "html" | "js" | "mjs" | "json" | "webmanifest" | "svg" | "txt" | "wasm"
    )
}

fn rust_string_literal(value: &str) -> String {
    format!("{value:?}")
}
