use std::env;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

const FALLBACK_INDEX: &str = r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>termd</title>
    <style>
      body { font-family: system-ui, sans-serif; margin: 2rem; line-height: 1.5; }
      code { background: #f3f4f6; padding: 0.125rem 0.25rem; border-radius: 0.25rem; }
    </style>
  </head>
  <body>
    <h1>termd Web</h1>
    <p>这个二进制没有嵌入已构建的 Web UI。发布构建会自动嵌入 <code>termui/frontend/dist</code>。</p>
  </body>
</html>
"#;

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-env-changed=TERMD_WEB_SOURCE_DIR");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let embedded_dir = out_dir.join("embedded-web");
    if embedded_dir.exists() {
        fs::remove_dir_all(&embedded_dir)?;
    }
    fs::create_dir_all(&embedded_dir)?;

    let files = match resolve_source_dir()? {
        Some(source_dir) => {
            emit_rerun_for_tree(&source_dir)?;
            copy_tree(&source_dir, &embedded_dir)?
        }
        None => {
            let fallback = embedded_dir.join("index.html");
            fs::write(&fallback, FALLBACK_INDEX)?;
            vec![PathBuf::from("index.html")]
        }
    };

    write_generated_assets(&out_dir, &files)?;
    Ok(())
}

fn resolve_source_dir() -> Result<Option<PathBuf>, Box<dyn Error>> {
    if let Some(raw) = env::var_os("TERMD_WEB_SOURCE_DIR") {
        let path = PathBuf::from(raw);
        let resolved = if path.is_absolute() {
            path
        } else {
            env::current_dir()?.join(path)
        };
        if has_index_html(&resolved) {
            return Ok(Some(resolved));
        }
    }

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let workspace_dist = manifest_dir.join("../termui/frontend/dist");
    if has_index_html(&workspace_dist) {
        return Ok(Some(workspace_dist));
    }

    Ok(None)
}

fn has_index_html(path: &Path) -> bool {
    path.join("index.html").is_file()
}

fn emit_rerun_for_tree(path: &Path) -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-changed={}", path.display());
    for entry in fs::read_dir(path)? {
        let entry = entry?;
        let child = entry.path();
        if child.is_dir() {
            emit_rerun_for_tree(&child)?;
        } else {
            println!("cargo:rerun-if-changed={}", child.display());
        }
    }
    Ok(())
}

fn copy_tree(source: &Path, dest: &Path) -> Result<Vec<PathBuf>, Box<dyn Error>> {
    let mut files = Vec::new();
    copy_tree_inner(source, source, dest, &mut files)?;
    files.sort();
    Ok(files)
}

fn copy_tree_inner(
    root: &Path,
    source: &Path,
    dest: &Path,
    files: &mut Vec<PathBuf>,
) -> Result<(), Box<dyn Error>> {
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let source_path = entry.path();
        let rel_path = source_path.strip_prefix(root)?.to_path_buf();
        let dest_path = dest.join(&rel_path);
        if source_path.is_dir() {
            fs::create_dir_all(&dest_path)?;
            copy_tree_inner(root, &source_path, dest, files)?;
        } else {
            if let Some(parent) = dest_path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::copy(&source_path, &dest_path)?;
            files.push(rel_path);
        }
    }
    Ok(())
}

fn write_generated_assets(out_dir: &Path, files: &[PathBuf]) -> Result<(), Box<dyn Error>> {
    let mut generated = String::new();
    generated.push_str("// @generated by termweb/build.rs\n");
    generated.push_str("pub(crate) fn embedded_asset(path: &str) -> Option<&'static [u8]> {\n");
    generated.push_str("    match path {\n");
    for file in files {
        let rel = file.to_string_lossy().replace('\\', "/");
        let rel_literal = rust_string_literal(&rel);
        let include_suffix = rust_string_literal(&format!("/embedded-web/{rel}"));
        generated.push_str("        ");
        generated.push_str(&rel_literal);
        generated.push_str(" => Some(include_bytes!(concat!(env!(\"OUT_DIR\"), ");
        generated.push_str(&include_suffix);
        generated.push_str("))),\n");
    }
    generated.push_str("        _ => None,\n");
    generated.push_str("    }\n");
    generated.push_str("}\n");

    fs::write(out_dir.join("assets.rs"), generated)?;
    Ok(())
}

fn rust_string_literal(value: &str) -> String {
    format!("{value:?}")
}
